import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { CONFIG_DIR, CONFIG_FILE, type AffitorConfig } from "../types.js";

function getConfigDir(cwd?: string): string {
  return join(cwd ?? process.cwd(), CONFIG_DIR);
}

function getConfigPath(cwd?: string): string {
  return join(getConfigDir(cwd), CONFIG_FILE);
}

export function configExists(cwd?: string): boolean {
  return existsSync(getConfigPath(cwd));
}

export function readConfig(cwd?: string): AffitorConfig {
  const path = getConfigPath(cwd);
  if (!existsSync(path)) {
    throw new ConfigNotFoundError(resolve(cwd ?? process.cwd()));
  }
  const raw = readFileSync(path, "utf-8");
  return JSON.parse(raw) as AffitorConfig;
}

export function writeConfig(config: AffitorConfig, cwd?: string): void {
  const dir = getConfigDir(cwd);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(getConfigPath(cwd), JSON.stringify(config, null, 2) + "\n");
}

export function updateConfig(
  updates: Partial<AffitorConfig>,
  cwd?: string,
): AffitorConfig {
  const config = readConfig(cwd);
  const updated = { ...config, ...updates };
  writeConfig(updated, cwd);
  return updated;
}

export function writeEnvExample(
  config: AffitorConfig,
  cwd?: string,
): void {
  const dir = getConfigDir(cwd);
  const content = `# Affitor Tracking — auto-generated by \`npx affitor init\`
# Add these to your .env file

AFFITOR_API_KEY=${config.api_key}
AFFITOR_PROGRAM_ID=${config.program_id}
${config.stripe_account_id ? `STRIPE_CONNECTED_ACCOUNT_ID=${config.stripe_account_id}` : "# STRIPE_CONNECTED_ACCOUNT_ID=  (run \`npx affitor setup stripe\` to connect)"}
`;
  writeFileSync(join(dir, ".env.example"), content);
}

export function writeSkillsFile(
  config: AffitorConfig,
  programName: string,
  cwd?: string,
): void {
  const dir = getConfigDir(cwd);
  const content = `# Affitor: ${programName}

> This file is auto-generated by \`npx affitor init\`.
> It is readable by Claude Code, Cursor, GitHub Copilot, Windsurf, Aider, and any AI coding tool that supports AGENTS.md.
> Docs: https://docs.affitor.com

## Project Context

This project uses Affitor for affiliate/partner tracking. Affitor tracks clicks, signups, and sales to attribute revenue to affiliate partners.

- **Program ID**: \`${config.program_id}\`
- **Domain**: \`${config.domain}\`
- **Commission**: ${formatCommission(config)}
- **Cookie Duration**: ${config.cookie.duration_days} days
- **API Base URL**: \`${config.api_url}\`
- **API Key**: stored in \`.affitor/.env.example\` as \`AFFITOR_API_KEY\`

## Integration Instructions

### 1. Click Tracking

Add this script tag to every page in \`<head>\`. It auto-detects affiliate visits via \`?aff=\` parameter and stores a first-party cookie.

\`\`\`html
<script src="${config.api_url}/js/affitor-tracker.js"
  data-affitor-program-id="${config.program_id}">
</script>
\`\`\`

For React/Next.js, use the SDK instead:

\`\`\`bash
npm install @affitor/tracker
\`\`\`

\`\`\`tsx
import { AffitorProvider } from '@affitor/tracker/react';

<AffitorProvider programId="${config.program_id}">
  {children}
</AffitorProvider>
\`\`\`

### 2. Signup/Lead Tracking

Call after user registration succeeds. The \`customerKey\` must be your internal user ID, reused in sale tracking.

\`\`\`javascript
// Browser-side (requires tracker script loaded)
await window.affitor.signup(user.id, user.email);
\`\`\`

\`\`\`bash
# Server-side alternative
curl -X POST ${config.api_url}/api/v1/track/lead \\
  -H "Authorization: Bearer $AFFITOR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"customer_key": "user_123", "email": "user@example.com"}'
\`\`\`

### 3. Sale/Revenue Tracking

**Option A: Stripe (recommended)** — run \`npx affitor setup stripe\` to auto-connect. Webhooks handle attribution automatically.

**Option B: Sale API (any payment provider)**

\`\`\`bash
curl -X POST ${config.api_url}/api/v1/track/sale \\
  -H "Authorization: Bearer $AFFITOR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "transaction_id": "txn_unique_id",
    "customer_key": "user_123",
    "amount_cents": 4900,
    "currency": "USD"
  }'
\`\`\`

Required fields: \`transaction_id\` (unique), \`amount_cents\` (positive integer), and at least one of \`customer_key\` or \`click_id\`.

**Option C: Stripe metadata (manual)** — add these fields to Stripe Checkout metadata:

\`\`\`javascript
metadata: {
  affitor_click_id: clickId,        // from cookie
  affitor_customer_key: user.id,    // your internal user ID
  program_id: '${config.program_id}'
}
\`\`\`

For subscriptions, duplicate the same metadata in \`subscription_data.metadata\`.

## Identifier Consistency

Use the same internal user ID everywhere:

| Context | Field Name |
|---|---|
| Browser signup helper | \`customerKey\` (1st argument) |
| Lead API | \`customer_key\` |
| Sale API | \`customer_key\` |
| Stripe metadata | \`affitor_customer_key\` |

## CLI Commands

\`\`\`bash
npx affitor status          # Check program health
npx affitor setup stripe    # Auto-connect Stripe via OAuth
npx affitor test click      # Send test click event
npx affitor test lead       # Send test lead event
npx affitor test sale       # Send test sale event
\`\`\`

## API Reference

| Endpoint | Method | Auth | Purpose |
|---|---|---|---|
| \`/api/v1/track/lead\` | POST | Bearer API key | Track signup/lead |
| \`/api/v1/track/sale\` | POST | Bearer API key | Track sale/payment |
| \`/api/v1/cli/status\` | GET | Bearer API key | Program health check |

## Conventions

- All amounts are in cents (e.g., $49.00 = 4900)
- \`transaction_id\` must be unique per sale (duplicate returns 409)
- Test mode: add \`"additional_data": {"test_mode": true}\` to skip commission creation
- CLI flags for automation: \`--no-interactive --json\`
`;

  // Write as AGENTS.md (universal standard) + skills.md (backward compat)
  writeFileSync(join(dir, "AGENTS.md"), content);
  writeFileSync(join(dir, "skills.md"), content);
}

export function appendToGitignore(cwd?: string): void {
  const gitignorePath = join(cwd ?? process.cwd(), ".gitignore");
  const entry = "\n# Affitor local config\n.affitor/.env\n";

  if (existsSync(gitignorePath)) {
    const content = readFileSync(gitignorePath, "utf-8");
    if (content.includes(".affitor/.env")) return;
    writeFileSync(gitignorePath, content + entry);
  }
}

function formatCommission(config: AffitorConfig): string {
  const { type, rate, duration_months } = config.commission;
  switch (type) {
    case "percent":
      return `${rate}% per sale`;
    case "fixed":
      return `$${rate} per sale`;
    case "recurring_percent":
      return `${rate}% recurring${duration_months ? ` for ${duration_months} months` : ""}`;
    case "recurring_fixed":
      return `$${rate} recurring${duration_months ? ` for ${duration_months} months` : ""}`;
  }
}

export class ConfigNotFoundError extends Error {
  constructor(dir: string) {
    super(
      `No Affitor config found in ${dir}.\n` +
        `Run ${"`npx affitor init`"} to set up your program.`,
    );
    this.name = "ConfigNotFoundError";
  }
}
