/**
 * Pure source transforms for the install wizard. No filesystem access — every
 * function takes file content and returns the new content, so they are easy to
 * unit test and never touch disk on their own. Injection is idempotent and
 * never overwrites existing code; an unrecognized structure returns
 * `unrecognized` so the wizard can fall back to printed instructions.
 */

const TRACKER_MARKER = "AffitorTracker";

export type InjectStatus = "injected" | "already" | "unrecognized";

export interface InjectResult {
  content: string;
  status: InjectStatus;
  /** Lines added (for the diff preview). Empty unless status === 'injected'. */
  added: string[];
}

/** The `<AffitorTracker />` client component written next to the entry file. */
export function trackerComponentSource(programId: string | number, useClientDirective: boolean): string {
  const idLiteral = typeof programId === "number" ? `${programId}` : JSON.stringify(programId);
  const prefix = useClientDirective ? "'use client';\n\n" : "";
  return `${prefix}import { useEffect } from 'react';
import { init } from 'affitor-sdk';

/**
 * Affitor affiliate tracking — auto-generated by \`affitor init\`.
 * Captures ?aff= attribution on every page. Safe to keep at the app root.
 */
export function ${TRACKER_MARKER}() {
  useEffect(() => {
    init({ programId: ${idLiteral} });
  }, []);
  return null;
}
`;
}

function importLineFor(importSpecifier: string): string {
  return `import { ${TRACKER_MARKER} } from '${importSpecifier}';`;
}

/** Add an import after the last existing top-level import (or at the very top). */
function addImport(content: string, importLine: string): string {
  if (content.includes(importLine)) return content;
  const importRe = /^import .*$/gm;
  let lastEnd = -1;
  let m: RegExpExecArray | null;
  while ((m = importRe.exec(content)) !== null) {
    lastEnd = m.index + m[0].length;
  }
  if (lastEnd === -1) return `${importLine}\n${content}`;
  return content.slice(0, lastEnd) + `\n${importLine}` + content.slice(lastEnd);
}

/**
 * App Router: insert `<AffitorTracker />` right after the opening `<body>` tag
 * of the root layout, and add the import.
 */
export function injectAppLayout(content: string, importSpecifier: string): InjectResult {
  if (content.includes(TRACKER_MARKER)) return { content, status: "already", added: [] };

  const bodyOpen = content.match(/<body[^>]*>/);
  if (!bodyOpen) return { content, status: "unrecognized", added: [] };

  const importLine = importLineFor(importSpecifier);
  const withImport = addImport(content, importLine);

  const tag = bodyOpen[0];
  const idx = withImport.indexOf(tag) + tag.length;
  const rendered = `        <${TRACKER_MARKER} />`;
  const injected = `${withImport.slice(0, idx)}\n${rendered}${withImport.slice(idx)}`;

  return { content: injected, status: "injected", added: [importLine, rendered.trim()] };
}

/**
 * Pages Router: wrap `<Component {...pageProps} />` so the tracker renders on
 * every page, and add the import.
 */
export function injectPagesApp(content: string, importSpecifier: string): InjectResult {
  if (content.includes(TRACKER_MARKER)) return { content, status: "already", added: [] };

  const compRe = /<Component\s+\{\.\.\.pageProps\}\s*\/>/;
  const match = content.match(compRe);
  if (!match) return { content, status: "unrecognized", added: [] };

  const importLine = importLineFor(importSpecifier);
  const withImport = addImport(content, importLine);

  const component = match[0];
  const replacement = `<>\n      <${TRACKER_MARKER} />\n      ${component}\n    </>`;
  const injected = withImport.replace(compRe, replacement);

  return { content: injected, status: "injected", added: [importLine, `<${TRACKER_MARKER} />`] };
}
