/**
 * Pure source transforms for the install wizard. No filesystem access — every
 * function takes file content and returns the new content, so they are easy to
 * unit test and never touch disk on their own. Injection is idempotent and
 * never overwrites existing code; an unrecognized structure returns
 * `unrecognized` so the wizard can fall back to printed instructions.
 */

const TRACKER_MARKER = "AffitorTracker";

export type InjectStatus = "injected" | "already" | "unrecognized";

export interface InjectResult {
  content: string;
  status: InjectStatus;
  /** Lines added (for the diff preview). Empty unless status === 'injected'. */
  added: string[];
}

/** The `<AffitorTracker />` client component written next to the entry file. */
export function trackerComponentSource(programId: string | number, useClientDirective: boolean): string {
  const idLiteral = typeof programId === "number" ? `${programId}` : JSON.stringify(programId);
  const prefix = useClientDirective ? "'use client';\n\n" : "";
  return `${prefix}import { useEffect } from 'react';
import { init } from '@affitor/sdk';

/**
 * Affitor affiliate tracking — auto-generated by \`affitor init\`.
 * Captures ?aff= attribution on every page. Safe to keep at the app root.
 */
export function ${TRACKER_MARKER}() {
  useEffect(() => {
    init({ programId: ${idLiteral} });
  }, []);
  return null;
}
`;
}

function importLineFor(importSpecifier: string): string {
  return `import { ${TRACKER_MARKER} } from '${importSpecifier}';`;
}

/**
 * Add an import after the last existing top-level import (or at the very top).
 *
 * Matches COMPLETE import statements — including multi-line destructured imports
 * (`import {\n  a,\n  b\n} from 'x';`) — so the new line lands AFTER the last
 * import, never spliced inside a destructure. An `import` starting at column 0
 * runs to its terminating `from '...'` / `from "..."` clause (or, for a
 * side-effect import, the bare `import '...'`), spanning newlines as needed.
 */
function addImport(content: string, importLine: string): string {
  if (content.includes(importLine)) return content;
  // ^import … from '…'|"…"  (multi-line tolerant), OR a side-effect import '…'.
  const importRe =
    /^import\b[\s\S]*?from\s+(['"])[^'"]*\1\s*;?|^import\s+(['"])[^'"]*\2\s*;?/gm;
  let lastEnd = -1;
  let m: RegExpExecArray | null;
  while ((m = importRe.exec(content)) !== null) {
    lastEnd = m.index + m[0].length;
  }
  if (lastEnd === -1) return `${importLine}\n${content}`;
  return content.slice(0, lastEnd) + `\n${importLine}` + content.slice(lastEnd);
}

/**
 * App Router: insert `<AffitorTracker />` right after the opening `<body>` tag
 * of the root layout, and add the import.
 */
export function injectAppLayout(content: string, importSpecifier: string): InjectResult {
  if (content.includes(TRACKER_MARKER)) return { content, status: "already", added: [] };

  const bodyOpen = content.match(/<body[^>]*>/);
  if (!bodyOpen) return { content, status: "unrecognized", added: [] };

  const importLine = importLineFor(importSpecifier);
  const withImport = addImport(content, importLine);

  const tag = bodyOpen[0];
  const idx = withImport.indexOf(tag) + tag.length;
  const rendered = `        <${TRACKER_MARKER} />`;
  const injected = `${withImport.slice(0, idx)}\n${rendered}${withImport.slice(idx)}`;

  return { content: injected, status: "injected", added: [importLine, rendered.trim()] };
}

/**
 * Pages Router: wrap `<Component {...pageProps} />` so the tracker renders on
 * every page, and add the import.
 */
export function injectPagesApp(content: string, importSpecifier: string): InjectResult {
  if (content.includes(TRACKER_MARKER)) return { content, status: "already", added: [] };

  const compRe = /<Component\s+\{\.\.\.pageProps\}\s*\/>/;
  const match = content.match(compRe);
  if (!match) return { content, status: "unrecognized", added: [] };

  const importLine = importLineFor(importSpecifier);
  const withImport = addImport(content, importLine);

  const component = match[0];
  const replacement = `<>\n      <${TRACKER_MARKER} />\n      ${component}\n    </>`;
  const injected = withImport.replace(compRe, replacement);

  return { content: injected, status: "injected", added: [importLine, `<${TRACKER_MARKER} />`] };
}

// ── Server-side: inject `affitor.trackSale(...)` into a Stripe webhook ──
//
// This edits PAYMENT code, so it is deliberately conservative: it only injects
// when it can recognize a clean `checkout.session.completed` shape with a single
// obvious session binding. Anything ambiguous → `unrecognized`, and the caller
// PRINTS the exact patch instead of forcing an edit. The transform is pure (no
// fs) and idempotent (a trackSale / @affitor/sdk/server marker → `already`).

/** Markers that mean a trackSale call (or the server import) is already wired. */
const TRACK_SALE_MARKER = "affitor.trackSale(";
const SERVER_IMPORT_MARKER = "@affitor/sdk/server";

/** The canonical Stripe webhook-verification call (Node SDK) we anchor on. */
const CONSTRUCT_EVENT_NEEDLE = "stripe.webhooks.constructEvent";

export interface InjectStripeOpts {
  /**
   * The provider sale snippet from `@affitor/recipes` (e.g.
   * `getRecipe(framework, 'stripe', 's2s').sale!.snippet`). The SDK import line
   * (`import { Affitor } from '@affitor/sdk/server';`) is stripped before
   * insertion — the inserted body is just the `affitor.trackSale({...})` call,
   * indented to match the matched session binding.
   */
  saleSnippet: string;
  /**
   * Module specifier for the `affitor` client import — e.g. `'../lib/affitor'`
   * or `'@/lib/affitor'`. When provided and status is 'injected', the transform
   * also adds `import { affitor } from '<importSpecifier>';` at the top of the
   * file (idempotent: skipped if that line is already present). Included in
   * `added[]` so the diff preview shows it.
   */
  importSpecifier?: string;
  /**
   * Optional indent override (spaces). When omitted, the indent of the matched
   * session-binding line is reused so the inserted call lines up with its block.
   */
  indent?: string;
}

/** Drop the recipe's leading `@affitor/sdk/server` import + its blank line. */
function saleCallBody(snippet: string): string {
  return snippet
    .replace(/^import \{ Affitor \} from '@affitor\/sdk\/server';\n+/, "")
    .trimEnd();
}

/** Re-indent a multi-line snippet body to a given base indent. */
function indentBody(body: string, indent: string): string {
  return body
    .split("\n")
    .map((line) => (line.length ? indent + line : line))
    .join("\n");
}

/** The import line for the affitor client given a module specifier. */
function affitorImportLine(importSpecifier: string): string {
  return `import { affitor } from '${importSpecifier}';`;
}

/**
 * Insert `affitor.trackSale(...)` into a Stripe webhook handler, right after the
 * verified `checkout.session.completed` session object is bound.
 *
 * CONSERVATIVE BY DESIGN — only injects when ALL of these hold (else returns
 * `unrecognized` so the caller prints the patch instead of editing payment code):
 *   1. The file contains `stripe.webhooks.constructEvent` (it really is a
 *      verified Stripe webhook — we never edit an unverified handler).
 *   2. There is a single `checkout.session.completed` reference to anchor on
 *      (the recipe's stripe snippet reads `session.*`, so the sale belongs in
 *      that case). Zero or multiple matches → unrecognized (ambiguous).
 *   3. After that anchor, exactly one line binds the event object to a name we
 *      can reuse — `const session = event.data.object …` (or `= session …`).
 *      The trackSale call is inserted on the line after that binding, at the
 *      binding's own indentation. No binding, or an unexpected variable name →
 *      unrecognized.
 *
 * Returns `already` when a `affitor.trackSale(` / `@affitor/sdk/server` marker is
 * already present (idempotent re-runs do nothing).
 */
export function injectStripeTrackSale(content: string, opts: InjectStripeOpts): InjectResult {
  // Idempotent: never double-inject.
  // Check for trackSale marker, server import marker, OR the affitor client import
  // (the specifier we would add) — any of these mean the file is already wired.
  const clientImportLine = opts.importSpecifier ? affitorImportLine(opts.importSpecifier) : null;
  if (
    content.includes(TRACK_SALE_MARKER) ||
    content.includes(SERVER_IMPORT_MARKER) ||
    (clientImportLine && content.includes(clientImportLine))
  ) {
    return { content, status: "already", added: [] };
  }

  // (1) Must be a verified Stripe webhook — anchor on constructEvent.
  if (!content.includes(CONSTRUCT_EVENT_NEEDLE)) {
    return { content, status: "unrecognized", added: [] };
  }

  // (2) Exactly one checkout.session.completed reference (the sale anchor).
  // Zero (some other event) or many (ambiguous which case) → bail.
  const completedRe = /checkout\.session\.completed/g;
  const completedMatches = content.match(completedRe);
  if (!completedMatches || completedMatches.length !== 1) {
    return { content, status: "unrecognized", added: [] };
  }
  const anchorIdx = content.indexOf("checkout.session.completed");

  // (3) After the anchor, find a single clean session binding to insert after.
  // Accept `const session = event.data.object …` or `const session = session …`
  // (cast variants). The variable MUST be named `session` — the recipe's stripe
  // snippet reads `session.client_reference_id` / `session.amount_total` /
  // `session.id`, so any other name would not compile.
  const after = content.slice(anchorIdx);
  const bindingRe = /^([ \t]*)const session\s*=\s*(?:event\.data\.object|session)\b[^\n]*$/m;
  const bindingMatch = after.match(bindingRe);
  if (!bindingMatch || bindingMatch.index === undefined) {
    return { content, status: "unrecognized", added: [] };
  }

  // Absolute offset of the end of the binding line (insertion point).
  const bindingLineStart = anchorIdx + bindingMatch.index;
  const bindingLineEnd = bindingLineStart + bindingMatch[0].length;

  const indent = opts.indent ?? bindingMatch[1] ?? "      ";
  const body = saleCallBody(opts.saleSnippet);
  if (!body.includes(TRACK_SALE_MARKER)) {
    // The provided snippet isn't a trackSale call — refuse rather than guess.
    return { content, status: "unrecognized", added: [] };
  }

  const block = indentBody(body, indent);
  const insertion = `\n${indent}// Affitor: report the sale (auto-added by \`affitor onboard\`)\n${block}`;
  const withSale = content.slice(0, bindingLineEnd) + insertion + content.slice(bindingLineEnd);

  // Also add the affitor client import when a specifier was provided.
  let finalContent = withSale;
  const added = insertion.split("\n").filter((l) => l.trim().length > 0);
  if (clientImportLine) {
    finalContent = addImport(withSale, clientImportLine);
    added.unshift(clientImportLine);
  }

  return { content: finalContent, status: "injected", added };
}
