import { readFileSync } from "node:fs";
import { join } from "node:path";
import { getRecipe, type Provider as RecipeProvider } from "@affitor/recipes";

/**
 * Server-side conversion tracking helpers for the wizard (@affitor/sdk/server path).
 * Pure functions (detection + generated source/snippets) — easy to unit test.
 * The wizard installs @affitor/sdk + scaffolds the client file, then PRINTS the
 * trackLead/trackSale snippets — it never edits auth/payment code (per PR-4 §9.3).
 *
 * The per-provider `sale` snippet is SOURCED FROM `@affitor/recipes` (the canonical
 * single source of truth read by CLI + MCP + docs). Do NOT re-inline the snippet
 * strings here — edit them in `@affitor/recipes` so all three surfaces stay in sync.
 */

export type PaymentProvider = "stripe" | "polar" | "lemonsqueezy" | "paddle" | "unknown";

const PROVIDER_DEPS: Record<Exclude<PaymentProvider, "unknown">, string[]> = {
  stripe: ["stripe", "@stripe/stripe-js"],
  polar: ["@polar-sh/sdk", "@polar-sh/nextjs", "@polar-sh/express"],
  lemonsqueezy: ["@lemonsqueezy/lemonsqueezy.js"],
  paddle: ["@paddle/paddle-node-sdk", "@paddle/paddle-js"],
};

/** Detect the advertiser's payment provider from package.json deps. */
export function detectPaymentProvider(cwd: string): PaymentProvider {
  let deps: Record<string, string> = {};
  try {
    const pkg = JSON.parse(readFileSync(join(cwd, "package.json"), "utf8"));
    deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  } catch {
    return "unknown";
  }
  for (const [provider, names] of Object.entries(PROVIDER_DEPS)) {
    if (names.some((n) => deps[n])) return provider as PaymentProvider;
  }
  return "unknown";
}

/** Source for the scaffolded `lib/affitor.ts` server client (a NEW file — safe to write). */
export function affitorClientSource(): string {
  return `import { Affitor } from '@affitor/sdk/server';

/**
 * Affitor server-side tracking client — auto-generated by \`affitor init\`.
 * Set AFFITOR_API_KEY in your environment (your program API key; keep it secret).
 */
export const affitor = new Affitor({ apiKey: process.env.AFFITOR_API_KEY ?? '' });
`;
}

export interface TrackingSnippets {
  importPath: string;
  lead: string;
  saleContext: string;
  sale: string;
  refund: string;
}

/**
 * The trackSale snippet body for a provider, sourced from the canonical
 * `@affitor/recipes` registry. We use framework "unknown" (the snippet body is
 * framework-independent) + mode "s2s" (so a sale snippet exists, not the
 * Connect/metadata-only path), then strip the leading `@affitor/sdk/server`
 * import + its blank line — the wizard prints that import via the lead snippet.
 */
function recipeSaleBody(provider: PaymentProvider): string {
  const recipe = getRecipe("unknown", provider as RecipeProvider, "s2s");
  const snippet = recipe.sale?.snippet ?? "";
  return snippet.replace(/^import \{ Affitor \} from '@affitor\/sdk\/server';\n\n/, "");
}

/**
 * Tailored trackLead + trackSale snippets. The sale snippet is provider-specific
 * (event name + field paths from the verified provider research). Printed, not
 * auto-applied.
 */
export function serverTrackingSnippets(
  provider: PaymentProvider,
  importPath = "@/lib/affitor",
): TrackingSnippets {
  const lead = [
    `import { affitor } from '${importPath}';`,
    `// After a user signs up — binds the affiliate click to your user id:`,
    `await affitor.trackLead({ customerExternalId: user.id, clickId: cookies.affitor_click_id });`,
  ].join("\n");

  // The trackSale snippet body is canonical in @affitor/recipes. We pull it from
  // there (framework "unknown" — the body is framework-independent; only the
  // inject_target differs, which the wizard doesn't print) and strip the SDK
  // import line the recipe prepends (the wizard already prints the import as part
  // of the lead snippet, via `importPath`).
  const sale = recipeSaleBody(provider);

  let saleContext: string;
  switch (provider) {
    case "polar":
      saleContext = "in your Polar webhook handler (event 'order.paid')";
      break;
    case "lemonsqueezy":
      saleContext = "in your Lemon Squeezy webhook handler (event 'order_created')";
      break;
    case "paddle":
      saleContext = "in your Paddle webhook handler (event 'transaction.completed')";
      break;
    case "stripe":
      saleContext =
        "Stripe: prefer Connect autocapture (`affitor stripe connect`). To track manually, in your checkout.session.completed handler";
      break;
    default:
      saleContext = "in your payment provider's webhook handler, when a payment succeeds";
  }

  const refund = [
    `// In your provider's refund webhook (e.g. order.refunded), reverse the commission`,
    `// (full refund → omit amount; partial → pass refundAmountCents):`,
    `await affitor.trackRefund({ invoiceId /* the same id you passed to trackSale */ });`,
  ].join("\n");

  return { importPath, lead, saleContext, sale, refund };
}
