import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Server-side conversion tracking helpers for the wizard (@affitor/node path).
 * Pure functions (detection + generated source/snippets) — easy to unit test.
 * The wizard installs @affitor/node + scaffolds the client file, then PRINTS the
 * trackLead/trackSale snippets — it never edits auth/payment code (per PR-4 §9.3).
 */

export type PaymentProvider = "stripe" | "polar" | "lemonsqueezy" | "paddle" | "unknown";

const PROVIDER_DEPS: Record<Exclude<PaymentProvider, "unknown">, string[]> = {
  stripe: ["stripe", "@stripe/stripe-js"],
  polar: ["@polar-sh/sdk", "@polar-sh/nextjs", "@polar-sh/express"],
  lemonsqueezy: ["@lemonsqueezy/lemonsqueezy.js"],
  paddle: ["@paddle/paddle-node-sdk", "@paddle/paddle-js"],
};

/** Detect the advertiser's payment provider from package.json deps. */
export function detectPaymentProvider(cwd: string): PaymentProvider {
  let deps: Record<string, string> = {};
  try {
    const pkg = JSON.parse(readFileSync(join(cwd, "package.json"), "utf8"));
    deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
  } catch {
    return "unknown";
  }
  for (const [provider, names] of Object.entries(PROVIDER_DEPS)) {
    if (names.some((n) => deps[n])) return provider as PaymentProvider;
  }
  return "unknown";
}

/** Source for the scaffolded `lib/affitor.ts` server client (a NEW file — safe to write). */
export function affitorClientSource(): string {
  return `import { Affitor } from '@affitor/node';

/**
 * Affitor server-side tracking client — auto-generated by \`affitor init\`.
 * Set AFFITOR_API_KEY in your environment (your program API key; keep it secret).
 */
export const affitor = new Affitor({ apiKey: process.env.AFFITOR_API_KEY ?? '' });
`;
}

export interface TrackingSnippets {
  importPath: string;
  lead: string;
  saleContext: string;
  sale: string;
}

/**
 * Tailored trackLead + trackSale snippets. The sale snippet is provider-specific
 * (event name + field paths from the verified provider research). Printed, not
 * auto-applied.
 */
export function serverTrackingSnippets(
  provider: PaymentProvider,
  importPath = "@/lib/affitor",
): TrackingSnippets {
  const lead = [
    `import { affitor } from '${importPath}';`,
    `// After a user signs up — binds the affiliate click to your user id:`,
    `await affitor.trackLead({ customerExternalId: user.id, clickId: cookies.affitor_click_id });`,
  ].join("\n");

  let saleContext: string;
  let sale: string;
  switch (provider) {
    case "polar":
      saleContext = "in your Polar webhook handler (event 'order.paid')";
      sale = [
        `await affitor.trackSale({`,
        `  customerExternalId: order.metadata.user_id ?? order.customer_id,`,
        `  amount: order.total_amount,        // integer cents`,
        `  invoiceId: order.id,`,
        `  saleType: order.subscription_id ? 'subscription' : 'payment',`,
        `});`,
      ].join("\n");
      break;
    case "lemonsqueezy":
      saleContext = "in your Lemon Squeezy webhook handler (event 'order_created')";
      sale = [
        `await affitor.trackSale({`,
        `  customerExternalId: payload.meta.custom_data?.user_id ?? data.attributes.user_email,`,
        `  amount: data.attributes.total,     // integer cents`,
        `  invoiceId: String(data.id),`,
        `});`,
      ].join("\n");
      break;
    case "paddle":
      saleContext = "in your Paddle webhook handler (event 'transaction.completed')";
      sale = [
        `await affitor.trackSale({`,
        `  customerExternalId: data.custom_data?.user_id,`,
        `  amount: Number(data.details.totals.total),   // cents`,
        `  invoiceId: data.id,`,
        `});`,
      ].join("\n");
      break;
    case "stripe":
      saleContext =
        "Stripe: prefer Connect autocapture (`affitor stripe connect`). To track manually, in your checkout.session.completed handler";
      sale = [
        `await affitor.trackSale({`,
        `  customerExternalId: session.client_reference_id,`,
        `  amount: session.amount_total,      // cents`,
        `  invoiceId: session.id,`,
        `});`,
      ].join("\n");
      break;
    default:
      saleContext = "in your payment provider's webhook handler, when a payment succeeds";
      sale = [
        `await affitor.trackSale({`,
        `  customerExternalId: user.id,`,
        `  amount: amountInCents,`,
        `  invoiceId: transactionId,`,
        `});`,
      ].join("\n");
  }

  return { importPath, lead, saleContext, sale };
}
